fairly distinct step

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -740,7 +740,13 @@ CURL_CPPFLAGS
 CURL_CONFIG
 BUILD_TRE_FALSE
 BUILD_TRE_TRUE
+TRE_LIBS
+TRE_CFLAGS
 PCRE2_CONFIG
+LIBDEFLATE_LIBS
+LIBDEFLATE_CFLAGS
+ZSTD_LIBS
+ZSTD_CFLAGS
 LZMA_LIBS
 LZMA_CFLAGS
 TIRPC_CPPFLAGS
@@ -1238,7 +1244,13 @@ SHLIB_CXX26LD
 SHLIB_CXX26LDFLAGS
 XMKMF
 LZMA_CFLAGS
-LZMA_LIBS'
+LZMA_LIBS
+ZSTD_CFLAGS
+ZSTD_LIBS
+LIBDEFLATE_CFLAGS
+LIBDEFLATE_LIBS
+TRE_CFLAGS
+TRE_LIBS'
 
 
 # Initialize some variables set by options.
@@ -2115,6 +2127,14 @@ Some influential environment variables:
   XMKMF       Path to xmkmf, Makefile generator for X Window System
   LZMA_CFLAGS C compiler flags for LZMA, overriding pkg-config
   LZMA_LIBS   linker flags for LZMA, overriding pkg-config
+  ZSTD_CFLAGS C compiler flags for ZSTD, overriding pkg-config
+  ZSTD_LIBS   linker flags for ZSTD, overriding pkg-config
+  LIBDEFLATE_CFLAGS
+              C compiler flags for LIBDEFLATE, overriding pkg-config
+  LIBDEFLATE_LIBS
+              linker flags for LIBDEFLATE, overriding pkg-config
+  TRE_CFLAGS  C compiler flags for TRE, overriding pkg-config
+  TRE_LIBS    linker flags for TRE, overriding pkg-config
 
 Use these variables to override the choices made by 'configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -29831,7 +29851,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:29834: \"$ac_link\") >&5
+(eval echo $as_me:29854: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -29909,7 +29929,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:29912: \"$ac_link\") >&5
+(eval echo $as_me:29932: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -58175,250 +58195,169 @@ fi
 
 
 ## Zstd headers and libraries.
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for ZSTD_versionNumber in -lzstd" >&5
-printf %s "checking for ZSTD_versionNumber in -lzstd... " >&6; }
-if test ${ac_cv_lib_zstd_ZSTD_versionNumber+y}
-then :
-  printf %s "(cached) " >&6
-else case e in #(
-  e) ac_check_lib_save_LIBS=$LIBS
-LIBS="-lzstd  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
 
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.
-   The 'extern "C"' is for builds by C++ compilers;
-   although this is not generally supported in C code supporting it here
-   has little cost and some practical benefit (sr 110532).  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char ZSTD_versionNumber (void);
-#ifdef FC_DUMMY_MAIN
-#ifndef FC_DUMMY_MAIN_EQ_F77
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int FC_DUMMY_MAIN() { return 1; }
-#endif
-#endif
-int
-main (void)
-{
-return ZSTD_versionNumber ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_zstd_ZSTD_versionNumber=yes
-else case e in #(
-  e) ac_cv_lib_zstd_ZSTD_versionNumber=no ;;
-esac
+pkg_failed=no
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for libzstd >= 1.3.3" >&5
+printf %s "checking for libzstd >= 1.3.3... " >&6; }
+
+if test -n "$ZSTD_CFLAGS"; then
+    pkg_cv_ZSTD_CFLAGS="$ZSTD_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libzstd >= 1.3.3\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libzstd >= 1.3.3") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_ZSTD_CFLAGS=`$PKG_CONFIG --cflags "libzstd >= 1.3.3" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
 fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS ;;
-esac
+ else
+    pkg_failed=untried
 fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_zstd_ZSTD_versionNumber" >&5
-printf "%s\n" "$ac_cv_lib_zstd_ZSTD_versionNumber" >&6; }
-if test "x$ac_cv_lib_zstd_ZSTD_versionNumber" = xyes
-then :
-  have_zstd=yes
-else case e in #(
-  e) have_zstd=no ;;
-esac
+if test -n "$ZSTD_LIBS"; then
+    pkg_cv_ZSTD_LIBS="$ZSTD_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libzstd >= 1.3.3\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libzstd >= 1.3.3") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_ZSTD_LIBS=`$PKG_CONFIG --libs "libzstd >= 1.3.3" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
 fi
 
-if test "${have_zstd}" = yes; then
-         for ac_header in zstd.h
-do :
-  ac_fn_c_check_header_compile "$LINENO" "zstd.h" "ac_cv_header_zstd_h" "$ac_includes_default"
-if test "x$ac_cv_header_zstd_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_ZSTD_H 1" >>confdefs.h
- have_zstd=yes
-else case e in #(
-  e) have_zstd=no ;;
-esac
-fi
 
-done
-fi
-if test "x${have_zstd}" = xyes; then
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if zstd version >= 1.3.3" >&5
-printf %s "checking if zstd version >= 1.3.3... " >&6; }
-if test ${r_cv_have_zstd+y}
-then :
-  printf %s "(cached) " >&6
-else case e in #(
-  e) ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-r_save_LIBS="${LIBS}"
-LIBS="-lzstd ${LIBS}"
-if test "$cross_compiling" = yes
-then :
-  r_cv_have_zstd=no
-else case e in #(
-  e) cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
+if test $pkg_failed = yes; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
 
-#ifdef HAVE_ZSTD_H
-#include <zstd.h>
-#endif
-#include <stdlib.h>
-int main(void) {
-    exit(ZSTD_versionNumber() < 10303);
-}
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+                ZSTD_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libzstd >= 1.3.3" 2>&1`
+        else
+                ZSTD_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libzstd >= 1.3.3" 2>&1`
+        fi
+        # Put the nasty error message in config.log where it belongs
+        echo "$ZSTD_PKG_ERRORS" >&5
 
-_ACEOF
-if ac_fn_c_try_run "$LINENO"
-then :
-  r_cv_have_zstd=yes
-else case e in #(
-  e) r_cv_have_zstd=no ;;
-esac
-fi
-rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
-  conftest.$ac_objext conftest.beam conftest.$ac_ext ;;
-esac
-fi
-
-LIBS="${r_save_LIBS}"
-ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
- ;;
-esac
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $r_cv_have_zstd" >&5
-printf "%s\n" "$r_cv_have_zstd" >&6; }
-fi
-if test "x${r_cv_have_zstd}" = xno; then
-  have_zstd=no
-fi
-if test "x${have_zstd}" = xyes; then
+        have_zstd=no
+elif test $pkg_failed = untried; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+        have_zstd=no
+else
+        ZSTD_CFLAGS=$pkg_cv_ZSTD_CFLAGS
+        ZSTD_LIBS=$pkg_cv_ZSTD_LIBS
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
 
 printf "%s\n" "#define HAVE_ZSTD 1" >>confdefs.h
 
-  LIBS="-lzstd ${LIBS}"
-  # check if we can use single-shot decompression on stream-compressed files (was added as static in 1.4.0)
-  ac_fn_c_check_func "$LINENO" "ZSTD_decompressBound" "ac_cv_func_ZSTD_decompressBound"
-if test "x$ac_cv_func_ZSTD_decompressBound" = xyes
-then :
-  have_zstd_decompressbound=yes
-else case e in #(
-  e) have_zstd_decompressbound=no ;;
-esac
-fi
-
-  if test "x${have_zstd_decompressbound}" = xyes; then
+   CPPFLAGS="${CPPFLAGS} ${ZSTD_CFLAGS}"
+   LIBS="${ZSTD_LIBS} ${LIBS}"
+   if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libzstd >= 1.4.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libzstd >= 1.4.0") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
 
 printf "%s\n" "#define HAVE_ZSTD_DECOMPRESSBOUND 1" >>confdefs.h
 
-  fi
-# so far we don't require it, but we might
-#else
-#  AC_MSG_ERROR("libzstd library and headers are required")
+fi
 fi
 
 
 ## libdeflate headers and libraries.
 
-         for ac_header in libdeflate.h
-do :
-  ac_fn_c_check_header_compile "$LINENO" "libdeflate.h" "ac_cv_header_libdeflate_h" "$ac_includes_default"
-if test "x$ac_cv_header_libdeflate_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_LIBDEFLATE_H 1" >>confdefs.h
- have_libdeflate=yes
-else case e in #(
-  e) have_libdeflate=no ;;
-esac
+
+pkg_failed=no
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for libdeflate" >&5
+printf %s "checking for libdeflate... " >&6; }
+
+if test -n "$LIBDEFLATE_CFLAGS"; then
+    pkg_cv_LIBDEFLATE_CFLAGS="$LIBDEFLATE_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libdeflate\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libdeflate") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LIBDEFLATE_CFLAGS=`$PKG_CONFIG --cflags "libdeflate" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$LIBDEFLATE_LIBS"; then
+    pkg_cv_LIBDEFLATE_LIBS="$LIBDEFLATE_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libdeflate\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libdeflate") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LIBDEFLATE_LIBS=`$PKG_CONFIG --libs "libdeflate" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
 fi
 
-done
-if test "${have_libdeflate}" = yes; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for libdeflate_alloc_compressor in -ldeflate" >&5
-printf %s "checking for libdeflate_alloc_compressor in -ldeflate... " >&6; }
-if test ${ac_cv_lib_deflate_libdeflate_alloc_compressor+y}
-then :
-  printf %s "(cached) " >&6
-else case e in #(
-  e) ac_check_lib_save_LIBS=$LIBS
-LIBS="-ldeflate  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
 
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.
-   The 'extern "C"' is for builds by C++ compilers;
-   although this is not generally supported in C code supporting it here
-   has little cost and some practical benefit (sr 110532).  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char libdeflate_alloc_compressor (void);
-#ifdef FC_DUMMY_MAIN
-#ifndef FC_DUMMY_MAIN_EQ_F77
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int FC_DUMMY_MAIN() { return 1; }
-#endif
-#endif
-int
-main (void)
-{
-return libdeflate_alloc_compressor ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_deflate_libdeflate_alloc_compressor=yes
-else case e in #(
-  e) ac_cv_lib_deflate_libdeflate_alloc_compressor=no ;;
-esac
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS ;;
-esac
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_deflate_libdeflate_alloc_compressor" >&5
-printf "%s\n" "$ac_cv_lib_deflate_libdeflate_alloc_compressor" >&6; }
-if test "x$ac_cv_lib_deflate_libdeflate_alloc_compressor" = xyes
-then :
-  have_libdeflate=yes
-else case e in #(
-  e) have_libdeflate=no ;;
-esac
-fi
 
+if test $pkg_failed = yes; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
 fi
-if test "x${r_cv_have_libdeflate}" = xno; then
-  have_libdeflate=no
-fi
-if test "x${have_libdeflate}" = xyes; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+        if test $_pkg_short_errors_supported = yes; then
+                LIBDEFLATE_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libdeflate" 2>&1`
+        else
+                LIBDEFLATE_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libdeflate" 2>&1`
+        fi
+        # Put the nasty error message in config.log where it belongs
+        echo "$LIBDEFLATE_PKG_ERRORS" >&5
+
+        have_libdeflate=no
+elif test $pkg_failed = untried; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+        have_libdeflate=no
+else
+        LIBDEFLATE_CFLAGS=$pkg_cv_LIBDEFLATE_CFLAGS
+        LIBDEFLATE_LIBS=$pkg_cv_LIBDEFLATE_LIBS
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 printf "%s\n" "yes" >&6; }
-  LIBS="-ldeflate ${LIBS}"
 
 printf "%s\n" "#define HAVE_LIBDEFLATE 1" >>confdefs.h
 
+     CPPFLAGS="${CPPFLAGS} ${LIBDEFLATE_CFLAGS}"
+     LIBS="${LIBDEFLATE_LIBS} ${LIBS}"
 fi
 
 
@@ -58793,85 +58732,81 @@ fi
 
 ## tre headers and libraries.
 if test "x${use_system_tre}" = xyes; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for tre_regncompb in -ltre" >&5
-printf %s "checking for tre_regncompb in -ltre... " >&6; }
-if test ${ac_cv_lib_tre_tre_regncompb+y}
-then :
-  printf %s "(cached) " >&6
-else case e in #(
-  e) ac_check_lib_save_LIBS=$LIBS
-LIBS="-ltre  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
 
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.
-   The 'extern "C"' is for builds by C++ compilers;
-   although this is not generally supported in C code supporting it here
-   has little cost and some practical benefit (sr 110532).  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char tre_regncompb (void);
-#ifdef FC_DUMMY_MAIN
-#ifndef FC_DUMMY_MAIN_EQ_F77
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int FC_DUMMY_MAIN() { return 1; }
-#endif
-#endif
-int
-main (void)
-{
-return tre_regncompb ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_tre_tre_regncompb=yes
-else case e in #(
-  e) ac_cv_lib_tre_tre_regncompb=no ;;
-esac
+pkg_failed=no
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for tre" >&5
+printf %s "checking for tre... " >&6; }
+
+if test -n "$TRE_CFLAGS"; then
+    pkg_cv_TRE_CFLAGS="$TRE_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"tre\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "tre") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_TRE_CFLAGS=`$PKG_CONFIG --cflags "tre" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
 fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS ;;
-esac
+ else
+    pkg_failed=untried
 fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_tre_tre_regncompb" >&5
-printf "%s\n" "$ac_cv_lib_tre_tre_regncompb" >&6; }
-if test "x$ac_cv_lib_tre_tre_regncompb" = xyes
-then :
-  have_tre=yes
-else case e in #(
-  e) have_tre=no ;;
-esac
+if test -n "$TRE_LIBS"; then
+    pkg_cv_TRE_LIBS="$TRE_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"tre\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "tre") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_TRE_LIBS=`$PKG_CONFIG --libs "tre" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
 fi
 
-  if test "${have_tre}" = yes; then
-           for ac_header in tre/tre.h
-do :
-  ac_fn_c_check_header_compile "$LINENO" "tre/tre.h" "ac_cv_header_tre_tre_h" "$ac_includes_default"
-if test "x$ac_cv_header_tre_tre_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_TRE_TRE_H 1" >>confdefs.h
- have_tre=yes
-else case e in #(
-  e) have_tre=no ;;
-esac
-fi
 
-done
-  fi
-if test "x${have_tre}" = xyes; then
+
+if test $pkg_failed = yes; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+                TRE_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "tre" 2>&1`
+        else
+                TRE_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "tre" 2>&1`
+        fi
+        # Put the nasty error message in config.log where it belongs
+        echo "$TRE_PKG_ERRORS" >&5
+
+        have_tre=no
+elif test $pkg_failed = untried; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+        have_tre=no
+else
+        TRE_CFLAGS=$pkg_cv_TRE_CFLAGS
+        TRE_LIBS=$pkg_cv_TRE_LIBS
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
 
 printf "%s\n" "#define HAVE_TRE 1" >>confdefs.h
 
-  LIBS="-ltre ${LIBS}"
+     CPPFLAGS="${CPPFLAGS} ${TRE_CFLAGS}"
+     LIBS="${TRE_LIBS} ${LIBS}"
+     have_tre=yes
 fi
 else
   have_tre="no"
